name: EC2 auto deploy

on:
  push:
    branches:
      - main

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Deploy
          uses: actions/checkout@v2
          with:
              host: ${{ secrets.HOST_NAME }}         # Repository Secrets から取得
              username: ${{ secrets.USER_NAME }}     # Repository Secrets から取得
              port: ${{ secrets.SSH_PORT }}          # Repository Secrets から取得
              key: ${{ secrets.PRIVATE_KEY }}        # Repository Secrets から取得
              script: |
                cd /home/ec2-user/backlog-clone
                git pull origin main
          # run: |
          #  # SSH接続して、git pullする
          #  echo "${{ secrets.PRIVATE_KEY }}" > private_key
          #  chmod 600 private_key
          #  ssh -oStrictHostKeyChecking=no ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }} -i private_key "cd /home/ec2-user/backlog-clone && git fetch git@github.com:ryomasan/backlog-clone.git && git pull git@github.com:ryomasan/backlog-clone.git"
