name: Reusable Deploy Workflow

on:
  workflow_call:
    inputs:
      host:
        required: true
        type: string
      username:
        required: true
        type: string
      port:
        required: false
        type: string
        default: "22"
      key:
        required: true
        type: string
      script:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH Key
        run: |
          echo "${{ inputs.key }}" > private_key
          chmod 600 private_key

      - name: Execute Deployment Script
        run: |
          ssh -oStrictHostKeyChecking=accept-new -i private_key -p ${{ inputs.port }} ${{ inputs.username }}@${{ inputs.host }} "
            ${{ inputs.script }}
          "
