name: EC2 auto deploy

on:
  push:
    branches:
      - main

jobs:
    build:
      runs-on: ubuntu-latest
      
      steps:
        - name: Deploy
          # run: |
          #  # SSH接続して、git pullする
          #  echo "${{ secrets.PRIVATE_KEY }}" > private_key
          #  chmod 600 private_key
          #  ssh -oStrictHostKeyChecking=no ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }} -i private_key "cd /home/ec2-user/backlog-clone && git fetch git@github.com:ryomasan/backlog-clone.git && git pull git@github.com:ryomasan/backlog-clone.git"
