name: EC2 auto deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml # 再利用可能なワークフローを呼び出す
    with: # 再利用可能なワークフローに渡すパラメータ
      host: ${{ secrets.HOST_NAME }}
      username: ${{ secrets.USER_NAME }}
      port: ${{ secrets.SSH_PORT }}
      key: ${{ secrets.PRIVATE_KEY }}
      script: |
        cd ${{ secrets.DEPLOY_DIR }}
        git pull origin main
